# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lol"
  lol:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    outputs:
      sha2_lol: ${{ steps.sha2_file_lol.outputs.sha_lol}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get SHA2-256SUMS for lol.txt
        id: sha2_file_lol
        env:
          SHA256_lol: ${{ hashFiles('test2/lol.txt') }}
        run: echo "::set-output name=sha_lol::$SHA256_lol"
        
# This workflow contains a single job called "lvl"
  lvl:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    outputs:
      sha2_lvl: ${{ steps.sha2_file_lvl.outputs.sha_lvl}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get SHA2-256SUMS for lvl.txt
        id: sha2_file_lvl
        env:
          SHA256_lvl: ${{hashFiles('test2/lvl.txt')}}
        run: echo "::set-output name=sha_lvl::$SHA256_lvl" 
        
# This workflow contains a single job called "final"
  final:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [lol, lvl]
    outputs:
      git_sha: ${{ steps.git_hash.outputs.git7}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prepare Git hash
        id: git_hash
        run: |
          git7=$(echo ${{github.sha}} | cut -c 1-7)
          echo "::set-output name=git7::$git7"
      
      - name: SHA2-256SUMS overview
        run: |
          echo ${{ needs.lol.outputs.sha2_lol }}
          echo ${{ needs.lvl.outputs.sha2_lvl }}
          
      - name: Make SHA2-256SUMS file
        env:
          SHA2_lo: ${{ needs.lol.outputs.sha2_lol }}
          SHA2_lv: ${{ needs.lvl.outputs.sha2_lvl }}
        run: |
          echo "$SHA2_lo lol.txt" > SHA2-256SUMS
          echo "$SHA2_lv lvl.txt" > SHA2-256SUMS
          echo "random_Text" >> SHA2-256SUMS
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.git_hash.outputs.git7 }}
          release_name: test_actions ${{ outputs.git_sha }}
          body: |
            test_actions
          draft: false
          prerelease: false
        
      - name: Upload 256SUMS file
        id: upload-sums
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SHA2-256SUMS
          asset_name: SHA2-256SUMS
          asset_content_type: text/plain
